server:
  port: 8001

spring:
  application:
    name: customer-service
    version: 1.0.0
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://localhost:5432/easyshop
    username: postgres
    password: password

  jpa:
     hibernate:
        ddl-auto : create-drop
eureka: 
  instance:
     preferIpAddress: true
            
---
spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://${DB_PORT_5432_TCP_ADDR}:5432/easyshop
        
eureka:
   profiles: container
   instance:
      preferIpAddress: true 
   client:
      serviceUrl:
          defaultZone: http://${EU_PORT_8761_TCP_ADDR}:8761/eureka/      