server:
  port: 9000

spring:
  application:
    name: api-gateway
    version: 1.0.0
  mvc:
    throw-exception-if-no-handler-found: true

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
zuul:
  routes:
    customer:
      path: /api/customer/**
      serviceId: customer-service
    order:
      path: /api/order/**
      serviceId: order-service
    product:
      path: /api/product/**
      serviceId: product-service      
          
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

